# @format

name: GitHub Classroom Workflow

on:
  # schedule:
  #   - cron: '0 */1 * * *'
  push:
    branches:
      - master

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install pkg
        run: |
          cd spider && npm install
      - name: create env file
        run: |
          echo TOKEN=${{ secrets.TOKEN }} >> spider/.env
          echo SESSION_TOKEN=${{ secrets.SESSION_TOKEN }} >> spider/.env
      - name: run test
        run: |
          cd spider && npm start